#!/bin/bash

assertPass(){
$@
assertEquals 'assertPass failed' 0 $?
}

assertFail(){
$@
assertEquals 'assertFail failed' 1 $?
}

assertFileContains(){
    egrep $2 $1 | grep -v 'grep' &>/dev/null
    assertEquals 'Missing content in file' 0 $?
}
assertFileNotContains(){
    egrep $2 $1 | grep -v 'grep' &>/dev/null
    assertEquals 'File should not contain the keyword' 1 $?
}

. $(dirname $0)/../lib/shunit2
